services:
  brapi-postgres:
    container_name: brapi-postgres
    image: postgres:latest
    ports:
      - 5430:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
#      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 3030:8080